include:
  - stacks/chat/compose.yaml
  - stacks/dashboard/compose.yaml
  - stacks/ente/compose.yaml
  - stacks/monitoring/compose.yaml
  - stacks/music/compose.yaml
  - stacks/proxy/compose.yaml
  - stacks/secret/compose.yaml
