services:
  vaultwarden:
    image: vaultwarden/server:1.37.3
    environment:
      DOMAIN: https://secret.ocd.beauty
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
    volumes:
      - /srv/vaultwarden/data:/data
    restart: unless-stopped
    labels:
      glance.icon: sh:vaultwarden-light
      glance.name: Vaultwarden
      glance.url: https://secret.ocd.beauty
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
