services:
  vaultwarden-server:
    image: vaultwarden/server:1.37.3
    restart: unless-stopped
    environment:
      DOMAIN: https://secret.ocd.beauty
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
    networks:
      - proxy
    volumes:
      - /srv/vaultwarden/data:/data
    security_opt:
      - no-new-privileges:true
    labels:
      glance.icon: sh:vaultwarden-light
      glance.name: Vaultwarden
      glance.url: https://secret.ocd.beauty

networks:
  proxy:
    external: true
