services:
  caddy:
    image: caddy:2.11.4
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - proxy
    volumes:
      - /srv/caddy/config:/config
      - /srv/caddy/data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
    labels:
      glance.hide: true
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
