services:
  caddy:
    image: caddy:2.11.4
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /srv/caddy/config:/config
      - /srv/caddy/data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    security_opt:
      - no-new-privileges:true
    labels:
      glance.hide: true

networks:
  proxy:
    external: true
