x-common: &common
  restart: unless-stopped
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true

services:
  navidrome:
    <<: *common
    image: deluan/navidrome:0.64.2
    volumes:
      - /srv/navidrome/data:/data
      - /srv/navidrome/music:/music:ro
    labels:
      glance.icon: sh:navidrome-light
      glance.name: Navidrome
      glance.url: https://music.ocd.beauty

  navidrome-dufs:
    <<: *common
    image: sigoden/dufs:v0.46.0
    command:
      - /data
      - -a
      - ${DUFS_USERNAME}:${DUFS_PASSWORD}@/:rw
      - -A
    volumes:
      - /srv/navidrome/music:/data
    labels:
      glance.icon: sh:dufs.webp
      glance.name: Navidrome's Dufs
      glance.url: https://file.music.ocd.beauty

networks:
  proxy:
    external: true
